project:
  title: "unir_master-ia_tfe_mejora-senal-astronomica"
format:
  typst:
    font-paths: ["assets/fonts"]
    mainfont: "Calibri"
    lang: es
    filters:
      - _filters/process_abstracts.lua
    template-partials:
      - typst-template.typ
      - typst-show.typ

    code-line-numbers: true

    tbl-cap-location: bottom
    tbl-pos: "H"

citeproc: false 
bibliography: references.bib
csl: apa.csl
nocite: |
  @*