project:
  title: "unir_master-ia_tfe_mejora-senal-astronomica"
format:
  typst:
    font-paths: ["_partials/assets/fonts"]
    mainfont: "Calibri"
    lang: es
    filters:
      - _filters/process_abstracts.lua
      - _filters/acronyms.lua
    template-partials:
      - typst-template.typ
      - typst-show.typ

    code-line-numbers: true

    tbl-cap-location: bottom
    tbl-pos: "H"

    include-after-body: _partials/bibliography.typ

citeproc: false